# BASE_DISTRIBUTION is used to switch between the old base distribution and distroless base images
ARG BASE_DISTRIBUTION=distroless

# Version is the base image version from the TLD Makefile
ARG BASE_VERSION=latest

# The following section is used as base image if BASE_DISTRIBUTION=default
FROM docker.io/istio/base:${BASE_VERSION} as default

# Install the latest sudo with fix for CVE-2021-3156
# This can likely be removed when updating to newer istio, see commit message.
RUN apt-get update && apt-get --only-upgrade install sudo

# The following section is used as base image if BASE_DISTRIBUTION=distroless
FROM gcr.io/distroless/static@sha256:627e2aade1375412f5e4d9f9e9ff47049feff37f0214625517a0298dc1d1adb0 as distroless

# This will build the final image based on either default or distroless from above
# hadolint ignore=DL3006
FROM ${BASE_DISTRIBUTION}

# install operator binary
COPY operator /usr/local/bin/

# add operator manifests
COPY manifests/ /var/lib/istio/manifests/

ENTRYPOINT ["/usr/local/bin/operator"]
